export const STRINGS = {
  brand: ' ShopSphere',
  nav: { home: 'Home', products: 'Products', blog: 'Blog', producers: 'For Producers' },
  heroTitle: 'Welcome to ShopSphere',
  landingSubtitle: 'Discover products inspired by',
  landingWordFarmingLead: 'Best',
  landingWordFarmingTail: ' Deals',
  landingWordArtisanLead: 'Unique',
  landingWordArtisanTail: ' Products',
  landingWordSustainableLead: 'Newest',
  landingWordSustainableTail: ' Collections ',
  featured: 'Featured products',
  fromOurBlog: 'From our blog',
  allProducts: 'All Products',
  blogTitle: 'Blog',
  selectPost: 'Select a post to read.',
  marketProducersTitle: 'Market for Producers',
  producersIntro: 'Welcome producers — connect directly with consumers, set fair prices, and tell your story.',
  footer: '© {year} ShopSphere. All rights reserved.',
  view: 'View',
  pricePrefix: 'Price:',
  accepted: 'Accepted',
  rejected: 'Rejected',
  accept: 'Accept',
  reject: 'Reject',
  markShipped: 'Mark shipped',

  // Product & Shop Labels
  soldBy: 'Sold by',
  visitShop: 'Visit shop',
  inStock: 'In stock',
  addToCart: 'Add to cart',
  reviews: 'Reviews',
  noReviewsYet: 'No reviews yet',
  loginToReview: 'Please log in as a buyer to leave a review.',
  yourName: 'Your name',
  yourRating: 'Your rating',
  yourReview: 'Your review',
  submitReview: 'Submit review',
  juteShop: 'Jute shop',
  productsAvailable: 'products available',
  productsAvailableCount: 'Products available: {count}',
  shopTitle: "{name}'s Shop",
  loadingShop: 'Loading shop…',
  backToMarketplace: 'Back to marketplace',
  aboutThisProducer: 'About this producer',
  aboutProducer: 'About',
  loadingStories: 'Loading stories…',
  noProducerStoriesYet: "This producer hasn't shared their story yet.",
  producerProfile: 'Producer profile',
  productsLabel: 'Products',
  averageRating: 'Average rating',
  storiesLabel: 'Stories',
  ratingLabel: 'Rating',
  thisShopHasNoProducts: 'This shop has no products yet.',
  continueShopping: 'Continue shopping',
  loading: 'Loading...',
  overview: 'Overview',
  products: 'Products',
  newOrders: 'New Orders',
  stories: 'Stories',
  totalRevenue: 'Total Revenue',
  salesTrends: 'Sales Trends (Last 7 Days)',
  dailySales: 'Daily sales',
  dailyIncome: 'Daily income',
  noSalesData: 'No sales data available',
  manageProducts: 'Manage Products',
  uploadProduct: 'Upload Product',
  editProfile: 'Edit Profile',
  customerReviews: 'Customer Reviews',
  noReviews: 'No customer reviews yet',
  platformControl: 'Platform Control',
  adminDashboard: 'Admin Dashboard',
  overseeMarketplace: 'Oversee producers, content, and marketplace health at a glance.',
  activeProducers: 'Active producers',
  productsListed: 'Products listed',
  communityPosts: 'Community posts',
  viewMarketplace: 'View marketplace',
  manageBlog: 'Manage blog',
  producerManagement: 'Producer Management',
  producerManagementSubtitle: 'Review and manage all producers on the platform',
  loadingProducers: 'Loading producers…',
  noProducersYet: 'No producers yet',
  viewProfile: 'View profile',
  contact: 'Contact',
  contactDetails: 'Contact details',
  accountInfo: 'Account info',
  joined: 'Joined',
  role: 'Role',
  active: 'Active',
  blocked: 'Blocked',
  viewShop: 'View shop',
  viewPosts: 'View posts',
  blockUser: 'Block user',
  unblockUser: 'Unblock user',
  confirmBlockUser: 'Block this user? They will not be able to post products or blogs.',
  confirmUnblockUser: 'Unblock this user?',
  failedToUpdateStatus: 'Failed to update status',
  failedToFetchUsers: 'Failed to fetch users',
  failedToLoadProducers: 'Failed to load producers',
  reviewProducers: 'Review all producers, approve signups, view profiles and shop pages.',
  manageProducersBtn: 'Manage producers',
  reviewContent: 'Review all blog posts, moderate user contributions, manage content guidelines.',
  manageContentBtn: 'Manage content',
  myProfile: 'My Profile',
  myOrders: 'My Orders',
  myAddresses: 'My Addresses',
  addNewAddress: 'Add new address',
  remove: 'Remove',
  noOrders: 'No orders yet',
  reorderButton: 'Reorder',
  producersInMarketplace: 'Producers in marketplace',
  favorites: 'Favorite Products',
  noFavorites: 'No favorites yet. Tap the heart on products to save them.',
  checkout: 'Checkout',
  orderSummary: 'Order Summary',
  categories: 'Categories',
  allCategories: 'All',
  bags: 'Bags',
  rugs: 'Rugs',
  mats: 'Mats',
  planters: 'Planters',
  homeDecor: 'Home Decor',
  accessories: 'Accessories',
  kitchen: 'Kitchen',
  garden: 'Garden',
  wallHangings: 'Wall Hangings',
  furniture: 'Furniture',
  cart: 'Cart',
  yourCartIsEmpty: 'Your cart is empty.',
  close: 'Close',
  clearCart: 'Clear',
  placeOrder: 'Place Order',
  login: 'Login',
  signup: 'Sign Up',
  dashboard: 'Dashboard',
  logout: 'Logout',
  signedInAs: 'Signed in as',
  account: 'Account',
  accessDenied: 'Access denied.',

  // Auth Pages
  welcomeBack: 'Welcome back',
  signIn: 'Sign in',
  emailOrPhone: 'Email or Phone',
  password: 'Password',
  signingIn: 'Signing in…',
  joinMarketplace: 'Join the marketplace',
  createAccount: 'Create your account',
  sellShareStories: 'Sell, share stories, and connect with buyers.',
  name: 'Name',
  email: 'Email',
  phone: 'Phone',
  phoneLabel: 'Phone',
  accountType: 'Account type',
  buyer: 'Buyer',
  producer: 'Producer',
  admin: 'Admin',
  password2: 'Password',
  confirmPassword: 'Confirm Password',
  createBtn: 'Create Account',
  creatingAccount: 'Creating account…',
  emailOrPhoneRequired: 'Please provide either an email or phone number.',
  loginToLikeOrComment: 'Please log in to like or comment.',
  like: 'Like',
  liked: 'Liked',
  likes: 'likes',
  comments: 'Comments',
  noCommentsYet: 'No comments yet',
  writeComment: 'Write a comment',
  commentPlaceholder: 'Write your comment…',
  postComment: 'Post comment',
  posting: 'Posting…',
  passwordsDoNotMatch: 'Passwords do not match.',
  alreadyHaveAccount: 'Already have an account?',
  dontHaveAccount: "Don't have an account?",

  // Upload & Manage Products
  addNewProduct: 'Add a new product',
  productName: 'Product name',
  priceBDT: 'Price (BDT)',
  description: 'Description',
  category: 'Category',
  stock: 'Stock',
  selectCategory: 'Select category',
  uploadImage: 'Upload image',
  coverImage: 'Cover image',
  addCoverPhoto: 'Add a photo',
  chooseFile: 'Choose file',
  uploadImageFile: 'Upload image file',
  imagePreview: 'Image preview',
  preview: 'Preview',
  productDescriptionPlaceholder: 'Material, size, care tips.',
  submit: 'Submit',
  cancel: 'Cancel',
  required: 'required',
  publishProduct: 'Publish product',
  uploading: 'Uploading…',
  backToDashboard: 'Back to dashboard',

  // Product Details Page
  productNotFound: 'Product not found',
  selectStarRating: 'Please select a star rating',
  reviewSuccess: 'Thanks for your review!',
  failedSubmitReview: 'Failed to submit review',
  productDetails: 'Product details',
  recommendedProducts: 'Recommended products',
  review: 'review',
  nameOptional: 'Name (optional)',
  shareExperience: 'Share your experience (optional)',
  noReviewsYetMessage: 'No reviews yet. Be the first to review this product.',
  anonymous: 'Anonymous',

  // Share Story
  shareYourStory: 'Share your story',
  tellYourStory: 'Tell your production journey, values, and products to the world.',
  storyTitle: 'Story Title',
  storyTitlePlaceholder: 'Give your story a captivating title...',
  excerpt: 'Excerpt',
  storyExcerptPlaceholder: 'Brief summary (optional)',
  storyContent: 'Story Content',
  storyContentPlaceholder: 'Tell your story... Share your experiences, challenges, and successes.',
  publishStory: 'Publish Story',
  publishing: 'Publishing…',
  posted: 'Story posted successfully!',
  titleAndContentRequired: 'Title and content are required',
  titleTooShort: 'Title should be at least 5 characters long',
  failedToPostStory: 'Failed to post story',
  or: 'or',
  imageURLPlaceholder: 'Image URL',
  characters: 'characters',

  // Manage Products
  myProducts: 'My Products',
  noProducts: 'No products yet',
  createFirstProduct: 'Create your first product to get started',
  manageProductsSubtitle: 'Edit, delete, or view all your products',
  edit: 'Edit',
  delete: 'Delete',
  save: 'Save',
  update: 'Update',
  updated: 'Product updated successfully!',
  deleted: 'Product deleted successfully!',
  confirmDelete: 'Are you sure you want to delete this product?',
  confirmDeletePost: 'Are you sure you want to delete this post?',
  failedToDeletePost: 'Failed to delete post',
  editProduct: 'Edit product',
  back: 'Back',
  actions: 'Actions',
  price: 'Price',
  failedToLoadProducts: 'Failed to load products',
  failedToFetchOrders: 'Failed to fetch orders',

  // Received Orders
  receivedOrders: 'Received Orders',
  noOrdersYet: 'No orders yet',
  new: 'new',
  saving: 'Saving…',
  deleting: 'Deleting…',
  noStoriesYet: 'No stories yet. Share your first story!',
  profilePhoto: 'Profile Photo',
  uploadFile: 'Upload File',
  savePhoto: 'Save Photo',
  changePhoto: 'Change Photo',
  orderID: 'Order ID',
  customer: 'Customer',
  items: 'Items',
  status: 'Status',
  date: 'Date',
  completed: 'Completed',
  pending: 'Pending',
  processing: 'Processing',
  shipped: 'Shipped',
  delivered: 'Delivered',
  orderNumber: 'Order #{num}',
  orderItemsCount: '{count} item(s)',
  paymentCash: 'Cash',
  paymentCard: 'Card',
  paymentMfs: 'MFS',

  // Checkout
  shippingAddress: 'Shipping Address',
  quickSelectAddress: 'Quick Select',
  useSavedAddress: '— Use a saved address —',
  saved: 'saved',
  default: 'Default',
  fullName: 'Full Name',
  enterFullName: 'Enter your full name',
  emailPlaceholder: 'your@email.com',
  phonePlaceholder: '01xxxxxxxxx',
  streetAddress: 'Street Address',
  addressPlaceholder: 'House number, street name, area',
  city: 'City',
  cityPlaceholder: 'Dhaka, Chittagong, etc',
  postalCode: 'Postal Code',
  optional: 'Optional',
  country: 'Country',
  nameRequired: 'Name is required',
  invalidEmail: 'Enter a valid email',
  invalidPhone: 'Enter a valid phone number',
  addressRequired: 'Address is required',
  cityRequired: 'City is required',
  countryRequired: 'Country is required',
  choosePaymentMethod: 'Choose Payment Method',
  selectPaymentMethod: "Select how you'd like to pay for your order",
  cashOnDelivery: 'Cash on Delivery',
  payOnDeliveryDesc: 'Pay when you receive your order',
  debitCreditCard: 'Debit/Credit Card',
  cardDesc: 'Visa, Mastercard, or American Express',
  mobileMoney: 'Mobile Money (MFS)',
  mfsDesc: 'bKash, Nagad, or Rocket',
  processingPayment: 'Processing your payment...',
  orderConfirmation: 'Order Confirmation',
  orderPlacedSuccess: 'Thank you! Your order has been placed.',
  paymentMethod: 'Payment method:',
  noItemsInCart: 'No items in cart.',
  correctFieldsError: 'Please correct the highlighted fields before placing your order.',
  checkoutSubtitle: 'Review your items and confirm shipping details',
  storageDisabledWarning: 'Warning: Storage disabled. Some features may not work.',
  checkoutCartEmptyProceed: 'Your cart is empty. Add items to proceed.',
  checkoutFailedToPlaceOrder: 'Failed to place order',
  checkoutCouldNotPlaceOrder: 'Could not place order. Please try again.',
  qty: 'Qty',
  totalAmount: 'Total Amount',
  valuedBuyer: 'valued buyer',
  bangladesh: 'Bangladesh',

  buyerDash: {
    workspace: 'Buyer Workspace',
    welcomeBack: 'Welcome back, {name}',
    heroSubtitle: 'Pick up where you left off: review your cart, check favorites, or browse new arrivals.',
    shortcuts: 'Your shortcuts',
    keepDetails: 'Keep your details up to date.',
    profileUpdated: 'Profile updated',
    failedUpdateProfile: 'Failed to update profile',
    quickCheckout: 'Quick selection at checkout.',
    noSavedAddresses: 'No saved addresses yet.',
    addressFallback: 'Address',
    setDefault: 'Set default',
    addAddress: 'Add address',
    labelExample: 'Label (e.g., Home, Office)',
    labelPlaceholder: 'Home',
    setAsDefault: 'Set as default',
    saveAddress: 'Save address',
    addressCityRequired: 'Address and city are required',
    failedAddAddress: 'Failed to add address',
    failedUpdateAddress: 'Failed to update address',
    failedDeleteAddress: 'Failed to delete address',
    deleteAddressConfirm: 'Delete this address?',
    moreShortcuts: 'More shortcuts',
    savedItemsTitle: 'Favorite Items',
    cartCheckoutTitle: 'Cart & checkout',
    cartCheckoutDesc: 'Check totals, addresses, and payment before placing an order.',
    openCheckout: 'Open checkout',
    producerStoriesTitle: 'Producer stories',
    producerStoriesDesc: 'Learn how your products are made and discover new creators.',
    readBlog: 'Read blog',
    myReviewsTitle: 'My Reviews',
    noMyReviews: 'No reviews yet. Review a product to see it here.',
    supportTitle: 'Support',
    help: 'Help'
  }
}

function getPath(obj, parts) {
  let cur = obj
  for (const p of parts) {
    if (!cur) return undefined
    cur = cur[p]
  }
  return cur
}

export function t(key, vars) {
  const parts = String(key || '').split('.')
  let value = getPath(STRINGS, parts)
  if (typeof value !== 'string') return key

  if (vars && typeof vars === 'object') {
    for (const k of Object.keys(vars)) {
      value = value.replace(`{${k}}`, String(vars[k]))
    }
  }
  return value
}
